package customerrors

const (
	// Database error codes
	ERROR_CODE_DATABASE_CONNECTION_FAILED     = 1001
	ERROR_CODE_DATABASE_PING_FAILED           = 1002
	ERROR_CODE_DATABASE_OPERATION_FAILED      = 1003
	ERROR_CODE_DATABASE_UNIQUE_KEY            = 1004
	ERROR_CODE_DATABASE_RECORD_NOT_FOUND      = 1005
	ERROR_CODE_DATABASE_INVALID_CONFIGURATION = 1006
)
